# Generated by Django 3.2.4 on 2022-03-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationUserReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('conversationId', models.ForeignKey(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.conversation')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversationuserreadstatus',
            constraint=models.UniqueConstraint(fields=('conversationId', 'userId'), name='conversation_user_read_status'),
        ),
    ]
