# Generated by Django 3.2.4 on 2022-03-21 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0003_auto_20220318_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationuser',
            name='lastRead',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
