# Generated by Django 3.2.4 on 2022-03-22 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0004_conversationuser_lastread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationuser',
            name='lastRead',
        ),
        migrations.AddField(
            model_name='conversationuser',
            name='lastReadDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conversationuser',
            name='lastReadMessageId',
            field=models.ForeignKey(db_column='messageId', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.message'),
            preserve_default=False,
        ),
    ]
