# Generated by Django 3.2.4 on 2022-03-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0005_auto_20220322_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationuser',
            old_name='lastReadMessageId',
            new_name='message',
        ),
    ]
